project_name: git-bump
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gitignore-cli
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

brews:
  - description: "release to homebrew"
    tap:
      owner: s14t284
      name: homebrew-tap
      token: "{{ .Env.ACCESS_TOKEN }}"
    homepage: "https://github.com/s14t284/gitignore-cli"
    install: |
      bin.install "gitignore-cli"